################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../tensorflow_lite/tensorflow/lite/micro/kernels/activations.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/add.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/arg_min_max.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/batch_to_space_nd.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/cast.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/ceil.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/comparisons.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/concatenation.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/conv.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/conv_common.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/conv_test_common.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv_common.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/dequantize.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/elementwise.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/elu.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/ethosu.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/exp.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/fill.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/floor.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected_common.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/kernel_runner.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/kernel_util.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/l2norm.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/logical.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/logistic.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/maximum_minimum.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/mul.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/neg.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/pack.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/pad.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/pooling.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/prelu.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/quantize.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/quantize_common.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/reduce.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/reshape.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/round.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/shape.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/softmax.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/softmax_common.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/space_to_batch_nd.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/split.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/split_v.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/squeeze.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/strided_slice.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/sub.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/svdf.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/svdf_common.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/tanh.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/transpose_conv.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/unpack.cc \
../tensorflow_lite/tensorflow/lite/micro/kernels/zeros_like.cc 

CC_DEPS += \
./tensorflow_lite/tensorflow/lite/micro/kernels/activations.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/add.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/arg_min_max.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/batch_to_space_nd.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/cast.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/ceil.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/comparisons.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/concatenation.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/conv.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/conv_common.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/conv_test_common.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv_common.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/dequantize.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/elementwise.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/elu.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/ethosu.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/exp.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/fill.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/floor.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected_common.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/kernel_runner.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/kernel_util.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/l2norm.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/logical.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/logistic.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/maximum_minimum.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/mul.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/neg.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/pack.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/pad.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/pooling.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/prelu.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/quantize.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/quantize_common.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/reduce.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/reshape.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/round.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/shape.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/softmax.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/softmax_common.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/space_to_batch_nd.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/split.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/split_v.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/squeeze.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/strided_slice.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/sub.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/svdf.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/svdf_common.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/tanh.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/transpose_conv.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/unpack.d \
./tensorflow_lite/tensorflow/lite/micro/kernels/zeros_like.d 

OBJS += \
./tensorflow_lite/tensorflow/lite/micro/kernels/activations.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/add.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/arg_min_max.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/batch_to_space_nd.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/cast.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/ceil.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/comparisons.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/concatenation.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/conv.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/conv_common.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/conv_test_common.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv_common.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/dequantize.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/elementwise.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/elu.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/ethosu.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/exp.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/fill.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/floor.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected_common.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/kernel_runner.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/kernel_util.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/l2norm.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/logical.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/logistic.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/maximum_minimum.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/mul.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/neg.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/pack.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/pad.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/pooling.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/prelu.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/quantize.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/quantize_common.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/reduce.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/reshape.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/round.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/shape.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/softmax.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/softmax_common.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/space_to_batch_nd.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/split.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/split_v.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/squeeze.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/strided_slice.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/sub.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/svdf.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/svdf_common.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/tanh.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/transpose_conv.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/unpack.o \
./tensorflow_lite/tensorflow/lite/micro/kernels/zeros_like.o 


# Each subdirectory must supply rules for building sources it contributes
tensorflow_lite/tensorflow/lite/micro/kernels/activations.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/activations.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/activations.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/add.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/add.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/add.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/arg_min_max.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/arg_min_max.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/arg_min_max.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/batch_to_space_nd.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/batch_to_space_nd.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/batch_to_space_nd.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/cast.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/cast.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/cast.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/ceil.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/ceil.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/ceil.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/circular_buffer.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/comparisons.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/comparisons.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/comparisons.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/concatenation.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/concatenation.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/concatenation.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/conv.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/conv.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/conv.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/conv_common.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/conv_common.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/conv_common.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/conv_test_common.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/conv_test_common.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/conv_test_common.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv_common.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv_common.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/depthwise_conv_common.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/dequantize.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/dequantize.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/dequantize.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/detection_postprocess.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/elementwise.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/elementwise.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/elementwise.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/elu.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/elu.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/elu.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/ethosu.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/ethosu.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/ethosu.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/exp.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/exp.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/exp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/fill.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/fill.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/fill.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/floor.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/floor.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/floor.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected_common.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected_common.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/fully_connected_common.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/hard_swish.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/kernel_runner.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/kernel_runner.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/kernel_runner.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/kernel_util.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/kernel_util.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/kernel_util.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/l2norm.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/l2norm.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/l2norm.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/logical.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/logical.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/logical.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/logistic.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/logistic.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/logistic.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/maximum_minimum.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/maximum_minimum.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/maximum_minimum.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/mul.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/mul.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/mul.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/neg.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/neg.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/neg.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/pack.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/pack.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/pack.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/pad.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/pad.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/pad.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/pooling.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/pooling.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/pooling.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/prelu.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/prelu.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/prelu.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/quantize.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/quantize.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/quantize.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/quantize_common.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/quantize_common.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/quantize_common.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/reduce.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/reduce.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/reduce.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/reshape.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/reshape.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/reshape.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/round.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/round.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/round.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/shape.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/shape.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/shape.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/softmax.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/softmax.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/softmax.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/softmax_common.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/softmax_common.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/softmax_common.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/space_to_batch_nd.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/space_to_batch_nd.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/space_to_batch_nd.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/split.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/split.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/split.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/split_v.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/split_v.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/split_v.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/squeeze.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/squeeze.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/squeeze.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/strided_slice.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/strided_slice.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/strided_slice.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/sub.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/sub.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/sub.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/svdf.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/svdf.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/svdf.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/svdf_common.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/svdf_common.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/svdf_common.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/tanh.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/tanh.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/tanh.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/transpose_conv.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/transpose_conv.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/transpose_conv.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/unpack.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/unpack.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/unpack.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
tensorflow_lite/tensorflow/lite/micro/kernels/zeros_like.o: ../tensorflow_lite/tensorflow/lite/micro/kernels/zeros_like.cc tensorflow_lite/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32L4R5xx -c -I../Core/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/flatbuffers/include" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/gemmlowp" -I"C:/Users/chitr/STM32CubeIDE/workspace_1.6.0/nucleo-l4r5zi-sine-tflite-test/tensorflow_lite/third_party/ruy" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"tensorflow_lite/tensorflow/lite/micro/kernels/zeros_like.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

